### ISSUE TITLE
Nice ❤️  what's the pypi for this? and does it use the same code as the gist?

### ISSUE THREAD

**Issue by simkimsia** [alingse/git-ssh-key#6]
i came over from the gist https://gist.github.com/gubatron/d96594d982c5043be6d4?permalink_comment_id=4081194#gistcomment-4081194

does it use the same code as the gist? or ?

**Comment by alingse** [comment]
here, https://pypi.org/project/git-ssh-key/

you can use pip to install it, I will edit my reply in the gist

```
pip install git-ssh-key
```

@simkimsia

**Comment by simkimsia** [comment]
What about your method?

> does it use the same code as the gist? or you follow something else

**Comment by alingse** [comment]
the same, just make it easier and auto, you can see How it works  here https://github.com/alingse/git-ssh-key#how-it-work

1. auto generate ssh key
2. auto add Domain  key path to the  `~/.ssh/config`(default)
3. manage the alias tag

https://github.com/alingse/git-ssh-key/blob/main/gitsshkey/main.py#L119-L122
